version: '3'

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/data:/app/src/data
      - ./src/models:/app/src/models
    depends_on:
      - prometheus
      - grafana
      - data_container

  data_container:
    build:
      context: .
      dockerfile: Dockerfile.data
    volumes:
      - ./src/data:/data
      - ./src/models:/data/models

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: