# Используем легкий базовый образ Alpine
FROM alpine:latest

# Создаем директории для данных
RUN mkdir -p /app/data

# Копируем данные из локальной папки в контейнер
COPY ./src/data /app/data

# Контейнер будет работать в фоновом режиме
CMD ["tail", "-f", "/dev/null"]