# Используем базовый образ Amazon Linux 2
FROM amazonlinux:2

# Создаем директорию для данных
RUN mkdir -p /data/models

# Копируем данные в контейнер
COPY src/data /data
COPY src/models /data/models

# Этот контейнер просто сохраняет данные, поэтому у него нет команд CMD или ENTRYPOINT.