name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to clone the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Docker build context (default is the current directory)
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops:latest

      # Logout from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout